package config

var Categories = map[string]string{
	".jpg":  "Images",
	".jpeg": "Images",
	".png":  "Images",
	".gif":  "Images",
	".bmp":  "Images",
	".tif":  "Images",
	".tiff": "Images",
	".svg":  "Images",
	".webp": "Images",
	".heic": "Images",
	".heif": "Images",
	".avif": "Images",
	".ico":  "Images",
	".cr2":  "Images",
	".nef":  "Images",

	".mp4":  "Videos",
	".mkv":  "Videos",
	".avi":  "Videos",
	".mov":  "Videos",
	".wmv":  "Videos",
	".webm": "Videos",
	".m4v":  "Videos",
	".flv":  "Videos",
	".mpeg": "Videos",
	".mpg":  "Videos",
	".3gp":  "Videos",

	".pdf":  "Documents",
	".doc":  "Documents",
	".docx": "Documents",
	".odt":  "Documents",
	".rtf":  "Documents",
	".txt":  "Documents",
	".md":   "Documents",
	".tex":  "Documents",

	".xls":  "Tableurs",
	".xlsx": "Tableurs",
	".ods":  "Tableurs",
	".csv":  "Tableurs",
	".tsv":  "Tableurs",

	".ppt":  "Presentations",
	".pptx": "Presentations",
	".odp":  "Presentations",

	".epub": "Livres",
	".mobi": "Livres",
	".azw3": "Livres",

	".mp3":  "Musique",
	".wav":  "Musique",
	".flac": "Musique",
	".aac":  "Musique",
	".m4a":  "Musique",
	".ogg":  "Musique",
	".opus": "Musique",
	".wma":  "Musique",
	".aiff": "Musique",

	".zip": "Archives",
	".rar": "Archives",
	".7z":  "Archives",
	".tar": "Archives",
	".gz":  "Archives",
	".bz2": "Archives",
	".xz":  "Archives",
	".tgz": "Archives",

	".go":   "Code",
	".py":   "Code",
	".js":   "Code",
	".ts":   "Code",
	".jsx":  "Code",
	".tsx":  "Code",
	".java": "Code",
	".c":    "Code",
	".cpp":  "Code",
	".h":    "Code",
	".hpp":  "Code",
	".cs":   "Code",
	".rs":   "Code",
	".rb":   "Code",
	".php":  "Code",
	".swift": "Code",
	".kt":   "Code",
	".scala": "Code",
	".sh":   "Code",
	".bat":  "Code",
	".ps1":  "Code",
	".sql":  "Code",
	".json": "Code",
	".yaml": "Code",
	".yml":  "Code",
	".toml": "Code",
	".xml":  "Code",
	".ini":  "Code",
	".cfg":  "Code",

	".ttf":   "Polices",
	".otf":   "Polices",
	".woff":  "Polices",
	".woff2": "Polices",

	".exe":      "Executables",
	".msi":      "Executables",
	".apk":      "Executables",
	".appimage": "Executables",
	".dmg":      "Executables",
	".pkg":      "Executables",
	".deb":      "Executables",
	".rpm":      "Executables",

	".psd":   "Design",
	".ai":    "Design",
	".sketch": "Design",
	".xd":    "Design",
}
